### ISSUE TITLE
Error when using with mongodb has authentication

### ISSUE THREAD

**Issue by jindov** [rwynn/monstache#101]
Recently, I init authentication for mongodb, and monstache can not connect to mongodb anymore with this error:
```
INFO 2018/09/08 07:35:00 Successfully connected to MongoDB version 3.6.6
INFO 2018/09/08 07:35:00 Successfully connected to Elasticsearch version 6.3.2
INFO 2018/09/08 07:35:00 Entering event loop
panic: Unable to get collection names
		for database local: not authorized on local to execute command { listCollections: 1, cursor: { batchSize: 0 }, $db: "local" }

goroutine 52 [running]:
github.com/rwynn/gtm.OpLogCollectionName(0xc4202d0680, 0xc4202620a0, 0x8, 0xc4202c8240)
	/home/vagrant/go/src/github.com/rwynn/gtm/gtm.go:693 +0x2d1
github.com/rwynn/gtm.(*Options).Fill(0xc4202620a0, 0xc4202d0680)
	/home/vagrant/go/src/github.com/rwynn/gtm/gtm.go:1147 +0x91
github.com/rwynn/gtm.TailOps(0xc4201c65a0, 0xc42001e4e0, 0xc4201da300, 0xa, 0x10, 0xc4202620a0, 0x0, 0x0)
	/home/vagrant/go/src/github.com/rwynn/gtm/gtm.go:739 +0xe0
created by github.com/rwynn/gtm.Start
	/home/vagrant/go/src/github.com/rwynn/gtm/gtm.go:1345 +0x847
```
this is my command:
`./monstache -mongo-url mongodb://user:pass@172.24.0.3:27017/mydb -elasticsearch-url http://172.24.0.9:9200`
Thanks

**Comment by jindov** [comment]
Closed, my bad
