### ISSUE TITLE
Running in HA mode causes a `panic: runtime error:`

### ISSUE THREAD

**Issue by rpong** [rwynn/monstache#267]
We are running 3 monstache instances (version 5).

MongoDB is hosted on MongoDB Atlas (v 4.0.10)
ElasticSearch is hosted by AWS (ElasticSearch Service) (v6.7.0).

We have an ASG with EC2s running the same configuration File.
We are running Monstache version 5.0.8

We were only able to start one of the instances, once started, the other 2 yields the following:

```INFO 2019/08/01 03:50:23 Started monstache version 5.0.8
INFO 2019/08/01 03:50:23 Successfully connected to MongoDB version 4.0.11
INFO 2019/08/01 03:50:23 Successfully connected to Elasticsearch version 6.7.0
INFO 2019/08/01 03:50:23 Sending systemd READY=1
WARN 2019/08/01 03:50:23 Systemd notification not supported (i.e. NOTIFY_SOCKET is unset)
INFO 2019/08/01 03:50:23 Joined cluster [redacted]
INFO 2019/08/01 03:50:23 Pausing work for cluster [redacted]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xf97169]

goroutine 91 [running]:
main.(*indexClient).startReadWait.func1(0xc0000e8f00)
	/home/vagrant/release/monstache/monstache.go:3786 +0x29
created by main.(*indexClient).startReadWait
	/home/vagrant/release/monstache/monstache.go:3785 +0x57```

**Comment by rpong** [comment]
Upgrading to 5.0.12 fixed our issue :)
